listOne = list()
listTwo = list()


x = int(input('Enter a number for the first list: '))
listOne.append(x)
x = int(input('Enter a number for the first list: '))
listOne.append(x)
x = int(input('Enter a number for the first list: '))
listOne.append(x)
x = int(input('Enter a number for the first list: '))
listOne.append(x)
x = int(input('Enter a number for the first list: '))
listOne.append(x)

x = int(input('Enter a number for the second list: '))
listTwo.append(x)
x = int(input('Enter a number for the second list: '))
listTwo.append(x)
x = int(input('Enter a number for the second list: '))
listTwo.append(x)
x = int(input('Enter a number for the second list: '))
listTwo.append(x)
x = int(input('Enter a number for the second list: '))
listTwo.append(x)
listThree = set(listOne).intersection(listTwo)
print('First List:' + str(listOne))
print('Second List:' + str(listTwo))
print('Third List:' + str(listThree))
