myList = list()
y = str(input('Enter a word: '))
myList.append(y)
y = str(input('Enter a word: '))
myList.append(y)
y = str(input('Enter a word: '))
myList.append(y)
y = str(input('Enter a word: '))
myList.append(y)
y = str(input('Enter a word: '))
myList.append(y)
z = (str(myList[0]) + ' ' + myList[1] + ' ' + myList[2] + ' ' + myList[3] + ' ' + myList[4])
print('Words: ' + str(myList))
print('One String: '+ z)
